# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false
minecraft_version=1.21.10
loader_version=0.18.2
loom_version=1.14-SNAPSHOT
mod_version=1.0.0
maven_group=org.multicoder.jotf
archives_base_name=juiceofthefruits
fabric_version=0.138.3+1.21.10