modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Multi-Coder-24/JuiceOfTheFruits/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://api.modrinth.com/updates/juice-of-the-fruits/forge_updates.json?neoforge=only"
displayURL="https://modrinth.com/project/juice-of-the-fruits"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile = "logo.png"

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"